config/routes.rb
InformaticsTodo::Application.routes.draw do
  resources :todos

  devise_for :users

  root 'todos#index'

  get "my_todos" => "todos#my_todos"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  extend Enumerize
  enumerize :status, in: [:new, :started, :done]
  belongs_to :requester, class_name: User
  belongs_to :assignee, class_name: User

  validates :requester_id, presence: true

  self.per_page = 10

  def deadline_exceeded?
    deadline < Date.today unless deadline.nil?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todos_requested, class_name: "Todo",
                             foreign_key: "requester_id"

  has_many :todos_assigned, class_name: "Todo",
                            foreign_key: "assignee_id"

  def name
    email && email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def self.sortable_by(*columns, options)
      unless options.kind_of? Hash
        columns << options
        options = {}
      end
      options = default_options_for_sorting.merge(options)

      # `sortable_by' might be configured with symbols,
      # but we'll deal with their string represenations
      # only.
      columns.map!(&:to_s)

      define_method(:sort_column) do
        sort = params[:sort]
        sort && columns.include?(sort) ? sort : options[:default]
      end

      # :sort_direction is registered only in case the
      # controller is `sortable_by'. There would not be
      # any point if we had an access for :sort_direction
      # but none columns were "registered" as :sortable_by.
      helper_method :sort_column, :sort_direction
    end

    def self.default_options_for_sorting
      { default: nil }
    end

    def sort_direction
      direction = params[:direction]
      direction && ["asc", "desc"].include?(direction) ? direction : "asc"
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit, :create, :update]

  respond_to :html

  # defined in ApplicationController
  # it registers helper_methods like :sort_column and :sort_direction
  sortable_by :description, :status, :requester, :assignee, default: :description

  def index
    @presenter = TodoPresenter.new(sort_column:    sort_column,
                                   sort_direction: sort_direction,
                                   page:           params[:page])
  end

  def my_todos
    @presenter = TodoPresenter.new(root:           current_user.todos_assigned,
                                   sort_column:    sort_column,
                                   sort_direction: sort_direction,
                                   page:           params[:page])

    render :index
  end

  def show
    respond_with(@todo)
  end

  def new
    @todo = Todo.new(requester: current_user)
    respond_with(@todo)
  end

  def edit
  end

  def create
    @todo = Todo.create(todo_params)
    respond_with(@todo)
  end

  def update
    @todo.update(todo_params)
    respond_with(@todo)
  end

  def destroy
    @todo.destroy
    respond_with(@todo)
  end

  private
    def todo_params
      params.require(:todo).permit(:description, :status, :requester_id, :assignee_id, :deadline)
    end

    def set_todo
      @todo = Todo.find(params[:id])
    end

    def set_users
      @users = User.order(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    column = column.to_s
    title ||= column.to_s.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, 
                   {:class => css_class}
  end

end

app/helpers/todos_helper.rb
module TodosHelper
  def format_stats(stats)
    stats.map { |status, count| "#{count} #{status}" }
         .join(", ")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InformaticsTodo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo, html: {class: 'form-horizontal'}) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, class: 'control-label' %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :status, class: 'control-label' %><br>
    <%= f.select :status, Todo.status.options, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :requester_id, class: 'control-label' %><br>
    <%= f.select :requester_id, @users.map{ |u| [u.name, u.id]}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :assignee_id, class: 'control-label' %><br>
    <%= f.select :assignee_id, @users.map{ |u| [u.name, u.id]}, class: 'form-control', include_blank: true %>
  </div>
  <div class="form-group">
    <%= f.label :deadline, class: 'control-label' %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<%= format_stats(@presenter.stats) %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable :description %></th>
      <th><%= sortable :status %></th>
      <th><%= sortable :requester %></th>
      <th><%= sortable :assignee %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @presenter.todos.each do |todo| %>
      <tr class="<%= todo.deadline_exceeded? ? "danger" : nil %>">
        <td><%= todo.description %></td>
        <td>
          <span class="label label-<%= if todo.status == 'done' then 'success'; elsif todo.status == 'started' then 'warning'; else 'default' end%>">
            <%= todo.status %>
          </span>
        </td>
        <td><%= todo.requester.try(:name) %></td>
        <td><%= todo.assignee.try(:name) %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @presenter.todos, renderer: BootstrapPagination::Rails %>

<br>

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<p>
  <strong>Requester:</strong>
  <%= @todo.requester.try(:name) %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @todo.assignee.try(:name) %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @todo.deadline %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>